### ISSUE TITLE
Update the CLI description

### ISSUE THREAD

**Issue by maximumspatium** [dgelessus/python-rsrcfork#9]
The description of the command-line interface found on the main page seems to be outdated.
The usage examples shown there don't longer work.
An update would be highly appreciated!
Thank you in advance!

**Comment by dgelessus** [comment]
Ah, looks like I haven't updated that section of the README in a long time - fixed that now (82951f5d8e52124417357a2fa61d45591f783358). The command-line help (`rsrcfork --help`) should be up-to-date though.

Thanks for the report!
